# Generated by Django 5.0.4 on 2024-05-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_remove_letting_address_delete_address_delete_letting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
