# Generated by Django 5.0.4 on 2024-05-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='letting',
            options={'verbose_name': 'Letting', 'verbose_name_plural': 'Lettings'},
        ),
    ]
