name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test-and-quality:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.2]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SENTRY_KEY_URL: ${{ secrets.SENTRY_KEY_URL }}
      run: |
        coverage run -m pytest ./oc_lettings_site
        coverage report
    - name: Run Quality
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SENTRY_KEY_URL: ${{ secrets.SENTRY_KEY_URL }}
      run: |
        flake8 ./oc_lettings_site
